theme: jekyll-theme-slate
name:  龍谷大学2020年度後期授業
title: 龍谷大学2020年度後期の授業ポータル
description: 龍谷大学2020年度後期の対面授業/オンライン授業/ハイブリッド授業 の個人的ポータル
gems:
  - jekyll-seo-tag
kramdown:
  extensions:
    - autolink
    - footnotes
    - smart
